# Generated by Django 3.2.14 on 2022-10-27 01:41

from django.db import migrations, models
import proveedores.models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20221026_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=proveedores.models.media_directory_path),
        ),
    ]
